/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d44e33ca046842f16aa4050
*
* You will get 10% discount for each one of your friends
* 
*/
package com.test.db.test_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE ScoresBase PLEASE EDIT ../Scores.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Scores object
 * 
 */
 
import org.bson.types.ObjectId;
import org.mongodb.morphia.annotations.Entity;
import java.util.Date;
import java.math.BigDecimal;
import java.util.List;
import java.util.ArrayList;

import org.mongodb.morphia.annotations.Id;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import com.test.utils.ObjectIdListSerializer;


//IMPORT RELATIONS
import com.test.db.test_db.entity.Interests;
import com.test.db.test_db.entity.Qualities;
import com.test.db.test_db.entity.User;

@Entity("Scores")
public class ScoresBase {
	
	@Id
	@JsonSerialize(using = ToStringSerializer.class)
	private ObjectId _id;
	
	// Attributes
	
	
	// Relations User
	@JsonSerialize(using = ToStringSerializer.class)
	private ObjectId User;
	
	
	
	// Relations m:m Interest
	@JsonSerialize(using = ObjectIdListSerializer.class)
	private List<ObjectId> Interest;
	
	// Relations m:m Quality
	@JsonSerialize(using = ObjectIdListSerializer.class)
	private List<ObjectId> Quality;
	
	

    // GETTER AND SETTER
    
	public ObjectId get_id() {
		return _id;
	}

	public void set_id(ObjectId id) {
		this._id = id;
	}


	

	
    
    // Relations 1:m User
	public ObjectId getUser() {
		return User;
	}

	public void setUser(ObjectId User) {
		this.User = User;
	}
    
    
    
    
    // Relations m:m Interest
	public List<ObjectId> getInterest() {
		return Interest;
	}

	public void setInterest(List<ObjectId> Interest) {
		this.Interest = Interest;
	}
	
    
    // Relations m:m Quality
	public List<ObjectId> getQuality() {
		return Quality;
	}

	public void setQuality(List<ObjectId> Quality) {
		this.Quality = Quality;
	}
	
    
}