/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5d44e33ca046842f16aa4050
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";

// Custom Actions


// START IMPORT ACTIONS
import QualitiesActions from "../redux/actions/QualitiesActions";
import ScoresActions from "../redux/actions/ScoresActions";

// END IMPORT ACTIONS

/** APIs

* actionsQualities.create
*	@description CRUD ACTION create
*
* actionsScores.findByQuality
*	@description CRUD ACTION findByQuality
*	@param Objectid key - Id della risorsa Quality da cercare
*
* actionsQualities.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id 
*
* actionsQualities.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*

**/

class QualitiesEdit extends Component {
  // Init qualities
  constructor(props) {
    super(props);
    this.state = {
      qualities: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsQualities.loadQualities(this.props.match.params.id);
      this.props.actionsScores.findByQuality(this.props.match.params.id);
    }
    
  }

  // Insert props qualities in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      qualities: props.qualities
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.qualities._id) {
      this.props.actionsQualities.saveQualities(this.state.qualities).then(data => {
        this.props.history.push("/qualitieses/");
      });
    } else {
      this.props.actionsQualities.createQualities(this.state.qualities).then(data => {
        this.props.history.push("/qualitieses/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Qualities Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="Name"
            label="Name"
            value={this.state.qualities.Name || ""}
            onChange={Utils.handleChange.bind(this, "qualities")}
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with Scores */}
          
          <h3>Scores</h3>
          {(!this.props.listScores || this.props.listScores.length === 0) && 
            <div>No Scores associated</div>
          }
          {this.props.listScores &&
            this.props.listScores.map((item, i) => {
              return (
                <Link to={"/scoress/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/qualitieses/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsQualities: bindActionCreators(QualitiesActions, dispatch),
    actionsScores: bindActionCreators(ScoresActions, dispatch),
  };
};

// Validate types
QualitiesEdit.propTypes = { 
  actionsQualities: PropTypes.object.isRequired,
  actionsScores: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    qualities: state.QualitiesEditReducer.qualities,
    listScores: state.QualitiesEditReducer.listScores
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(QualitiesEdit);
